language: node_js
node_js:
    - "node"
cache:
    directories:
        - "$HOME/google-cloud-sdk/"

env:
    global:
        - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH}
    matrix:
        - RUN_TESTS=true

install:
    - "./ci/install.sh"

script:
    - "./ci/build.sh"
    - "./ci/run_tests.sh"

after_success:
    - "./ci/build_firebase_config.sh"
    - "./ci/deploy.sh"
