runtime: python27
api_version: 1
threadsafe: yes
service: app

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/.*

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
